### ISSUE TITLE
Bad file hinting when using include_tasks

### ISSUE THREAD

**Issue by Xat59** [ansible-community/vscode-ansible#59]
Hi guys,

I am now using your plugin in version `0.3.0` and I really thanks you.
I just discovered an issue when there are a lint warning/error in a file that is included with `include_tasks`.

Let's see the `main.yml` file : 
```yaml
---
- name: Pre-processing checks
  include_tasks: pre-check.yml

```

Now, here is the `pre-check.yml` that has an indentation lint error on the last line, to trigger the lint message in the console : 
```yaml
- name: pre-check| clients list is empty
  fail:
    msg: "clients list is empty, please check configuration..."
  tags:
  - generate-rules

```

Ok so, let's see what the linter says : 

![image](https://user-images.githubusercontent.com/1276192/114168499-9a3b7580-9930-11eb-9204-10bf8e7eef84.png)

Regarding the error message, it seems that there is something bad on line 5 within `main.yml`. Actually, the error message is into the `pre-check.yml` included file.

Thanks guys !
